version: '3'
services:
  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    working_dir: /app/web/
    command: npm start
    volumes:
      - ./packages/web:/app/web/
      - /app/web/node_modules
      - /app/web/.next
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    working_dir: /app/api/
    command: npm start
    volumes:
      - ./packages/api:/app/api/
      - /app/api/node_modules
      - /app/api/dist