version: '3'
services:
  web:
    build:
      context: ../packages/web
      dockerfile: dev/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - api
    environment:
      PORT: 3000
      NODE_ENV: development
      CLIENT_API_HOST: http://localhost:8000
      DOCKER_API_HOST: http://api:8000
    env_file:
      - .env.dev
    ports:
      - '3000:3000'
    working_dir: /app/web/
    command: npm run dev
    volumes:
      - ../packages/web:/app/web/
      - /app/web/node_modules
  api:
    build:
      context: ../packages/api
      dockerfile: dev/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - postgres
    environment:
      FORCE_COLOR: 1
      NODE_ENV: development
      PORT: 8000
      POSTGRES_USER: local
      POSTGRES_PASSWORD: sw0rdf1sH
      POSTGRES_DB: mono
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    env_file:
      - .env.dev
    ports:
      - '8000:8000'
      - '9229:9229'
    working_dir: /app/api/
    command: npm run dev
    volumes:
      - ../packages/api:/app/api/
      - /app/api/node_modules
      # - /app/api/dist
  postgres:
    image: postgres:12.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: sw0rdf1sH
      POSTGRES_DB: mono